### ISSUE TITLE
Dark Forces II - Needs Directplay added for multiplayer

### ISSUE THREAD

**Issue by Amphiii** [legluondunet/MyLittleLutrisScripts#108]
After installing directplay manually, multiplayer works perfectly using [IPX wrapper](https://www.solemnwarning.net/ipxwrapper/) (didn't test TCP/IP)

I think it just needs something like this added to the install script:
```
- task:
    app: directplay
    description: Installing...
    name: winetricks
    prefix: $GAMEDIR
    silent: true
```
