### ISSUE TITLE
Beyond Good & Evil - Steam Deck and installation steps

### ISSUE THREAD

**Issue by psstoyanov** [legluondunet/MyLittleLutrisScripts#135]
Hi, I would like to create a new Lutris installer using only a couple of parts based on your wonderful script to improve the experience with the Steam Deck.

So, the reason for opening this ticket - the widescreen patch is actively breaking the usability on Steam Deck if installed through the desktop session.
To run the game in DeckUI after initially installing it in Desktop mode:
- The virtual display resolution has to be set to `800x1280` manually
- The resulting window is in the middle of the display (screenshot bellow)

![20220813_181531_HDR](https://user-images.githubusercontent.com/3979134/184505680-62312505-e350-46c2-8cd4-96ddb343d8b1.jpg)
![Lutris_BGE_desktop_install](https://user-images.githubusercontent.com/3979134/184505694-5b043a16-ad4c-47f8-9d6f-c81cf271a41c.png)

Using your installer by launching Lutris in DeckUI mode works as expected and there are no issues with launching the game or its orientation :100: 

![20220813_190933_HDR](https://user-images.githubusercontent.com/3979134/184505805-62032027-d29b-4a44-a99a-454754bac7d3.jpg)

On Steam Deck, the autogenerated GoG installer works great with the caveats being:
- Missing gamepad support
- Disabling DXVK is required to start `SettingsApplication.exe` (this applies for all installers for this game)
- Letter boxing
- The use of `virtual desktop` is not required

When it comes down to Wayland and DXVK the autogenerated GoG installer has:
- Missing gamepad support
- Disabling DXVK is required to start `SettingsApplication.exe`
- For systems using higher refresh rate displays, the following system flag is required `DXVK_FRAME_RATE: 60`
Note:
- The use of `virtualtual desktop` is not required

It's a bit early to say if enabling the cpu pinning would be needed - I've only tested the autogenerated GoG installer in the first few minutes.

I don't know if the use audiopatch is required compared to the autogenerated GoG script (haven't experienced issues with it yet) and overall, I think it would be cool to have a cleaner version with just gamepad settings.

I would like to ask for permission to submit a new installer on Lutris that is referencing the gamepad setup on your repository.
The new install script that I'm proposing would have the following form:

```
custom-name: Beyond Good & Evil - GOG 
files:
- goginstaller: N/A:Select the installer from GOG
  gppreadme: https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyond%20Good%20and%20Evil/gamepad%20profiles/bge_gamepad_readme.html
  gppsteam: https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyond%20Good%20and%20Evil/gamepad%20profiles/bge_steam.sccprofile
  gppx360: https://github.com/legluondunet/MyLittleLutrisScripts/raw/master/Beyond%20Good%20and%20Evil/gamepad%20profiles/bge_x360.gamecontroller.amgp
game:
  exe: _xXx_AUTO_WIN32_xXx_
installer:
- autosetup_gog_game: goginstaller
- merge:
    dst: $GAMEDIR/drive_c/GOG Games/Beyond Good and Evil/gamepad profiles/
    src: gppreadme
- merge:
    dst: $GAMEDIR/drive_c/GOG Games/Beyond Good and Evil/gamepad profiles/
    src: gppx360
- merge:
    dst: $GAMEDIR/drive_c/GOG Games/Beyond Good and Evil/gamepad profiles/
    src: gppsteam
- task:
    description: Please choose only your resolution, save and quit.
    executable: $GAMEDIR/drive_c/GOG Games/Beyond Good and Evil/SettingsApplication.exe
    name: wineexec
```

With the following technical notes:

> Basic GoG version, safe for installation from both Desktop and DeckUI session.
> Doesn't include widescreen or audio fixes.
>
> If you are unable to launch SettingsApplication.exe after first install, disable DXVK for the game.
> If you are on a desktop system and the audio is not synchronised, add the following system flag:
> `DXVK_FRAME_RATE 60`

I hope my request is reasonable and would provide users the choice between your more functional install script and a less functional but slightly more stable one :slightly_smiling_face:
